/**
 * svg-core.js
 *
 * JavaScript port of the canonical conversion algorithm that lives in
 * `svg_core.py`. The two MUST produce byte-identical output: `tests/fixtures/`
 * holds golden files that both the pytest and the node:test suites assert
 * against, so any drift between them fails CI.
 *
 * Algorithm (canonical — mirrored exactly in svg_core.py):
 *   0. Prepare each pixel: composite any transparency onto white (so a logo on
 *      a transparent background does not turn into a black square), then, in
 *      "bw" and "grayscale" modes, reduce it to one integer luma value. This
 *      lives in the core, not in the app, so both ports agree from the source
 *      pixels to the final file.
 *   1. Split the image into blocks of `blockSize = MAX_BLOCK_SIZE + 1 - detailLevel`.
 *   2. Average pixel colors inside each block (integer floor division).
 *   3. Posterize each channel to `colorLevels` values, range-preserving:
 *      0 stays 0 and 255 stays 255. In "bw" mode each channel is instead
 *      re-thresholded at BW_THRESHOLD so averaging a block of black and white
 *      pixels cannot leak grays into a mode that is meant to be binary.
 *   4. Run-length-encode each block row horizontally.
 *   5. Merge each run with the run directly above it when color, x and width
 *      match, producing rectangles merged in BOTH axes.
 *   6. Emit <g fill="..."> groups in first-appearance order.
 *
 * All arithmetic in steps 0-3 is integer-only over non-negative operands, so
 * `Math.floor(a / b)` here and `a // b` in Python agree exactly.
 *
 * Exposed as a UMD-ish module: works in a regular <script> tag
 * (`globalThis.SvgCore`), inside a Web Worker (`self.SvgCore`), and under
 * `require()` in Node.
 */
(function (root, factory) {
    "use strict";
    const api = factory();
    root.SvgCore = api;
    if (typeof module !== "undefined" && module.exports) {
        module.exports = api;
    }
})(typeof self !== "undefined" ? self : globalThis, function () {
    "use strict";

    const VALID_CONVERSION_TYPES = Object.freeze(["color", "bw", "grayscale"]);

    /** Grayscale value at or above which a pixel becomes white in "bw" mode. */
    const BW_THRESHOLD = 128;

    /**
     * Largest block edge, reached at detailLevel === MIN_DETAIL_LEVEL.
     * blockSize = MAX_BLOCK_SIZE + 1 - detailLevel, so detail 1 -> 10px blocks
     * (coarse) and detail 10 -> 1px blocks (every pixel kept).
     */
    const MAX_BLOCK_SIZE = 10;

    const MIN_DETAIL_LEVEL = 1;
    const MAX_DETAIL_LEVEL = 10;
    const DEFAULT_DETAIL_LEVEL = 5;

    /**
     * Number of distinct values kept per RGB channel. The resulting palette
     * holds colorLevels ** 3 colors (2 -> 8 colors, 6 -> 216 colors).
     */
    const MIN_COLOR_LEVELS = 2;
    const MAX_COLOR_LEVELS = 6;
    const DEFAULT_COLOR_LEVELS = 3;

    /**
     * Upper bound on blockCount(). Output size grows with the number of
     * blocks, not the source pixels: noisy input costs ~49 bytes per block, so
     * this caps the worst case near 200 MB — inside V8's maximum string length
     * instead of crashing the tab.
     */
    const MAX_BLOCKS = 4000000;

    /** ITU-R BT.601 luma weights, in thousandths (integer math keeps parity). */
    const GRAY_WEIGHTS = Object.freeze([299, 587, 114]);

    /** The generated file belongs to the user, so it only says what made it. */
    const DEFAULT_HEADER_COMMENTS = Object.freeze(["Generated by محول SVG"]);

    /** Bands between two onProgress calls aim for roughly this many updates. */
    const PROGRESS_UPDATES = 50;

    /**
     * Posterize one 0-255 channel to `colorLevels` evenly spaced values.
     *
     * Unlike naive `(v / step | 0) * step` truncation this is range-preserving:
     * 0 maps to 0 and 255 maps to 255 for every level count, so whites stay
     * white instead of collapsing to mid-gray. Integer half-up rounding keeps
     * it identical to the Python implementation.
     */
    function quantizeChannel(value, colorLevels) {
        const steps = colorLevels - 1;
        // round(value * steps / 255), half-up
        const index = Math.floor((value * steps * 2 + 255) / 510);
        // round(index * 255 / steps), half-up
        return Math.floor((index * 510 + steps) / (steps * 2));
    }

    /** Snap one channel back to pure black or white for "bw" mode. */
    function thresholdChannel(value) {
        return value >= BW_THRESHOLD ? 255 : 0;
    }

    /** Composite one channel with opacity `alpha` onto white, rounded half-up. */
    function flattenChannel(value, alpha) {
        return Math.floor((value * alpha + 255 * (255 - alpha) + 127) / 255);
    }

    /** Integer BT.601 luma, rounded half-up. Mirrors gray_value() in svg_core.py. */
    function grayValue(r, g, b) {
        return Math.floor(
            (r * GRAY_WEIGHTS[0] + g * GRAY_WEIGHTS[1] + b * GRAY_WEIGHTS[2] + 500) / 1000
        );
    }

    /** Number of blocks (an upper bound on rectangles) for these settings. */
    function blockCount(width, height, detailLevel) {
        const blockSize = MAX_BLOCK_SIZE + 1 - detailLevel;
        return Math.ceil(width / blockSize) * Math.ceil(height / blockSize);
    }

    /** Return { starts, ends } of the blocks covering `size` pixels. */
    function blockBounds(size, blockSize) {
        const starts = [];
        const ends = [];
        for (let start = 0; start < size; start += blockSize) {
            starts.push(start);
            ends.push(Math.min(start + blockSize, size));
        }
        return { starts: starts, ends: ends };
    }

    /**
     * Prepare (step 0), average and posterize one block row into a flat
     * [r, g, b, r, g, b, ...] array. `data` is RGBA and is never modified.
     */
    function averageBand(data, width, y0, y1, starts, ends, colorLevels, isBw, isGray) {
        const bandWidth = starts.length;
        const band = new Uint8Array(bandWidth * 3);

        for (let bx = 0; bx < bandWidth; bx++) {
            const x0 = starts[bx];
            const x1 = ends[bx];
            let rSum = 0;
            let gSum = 0;
            let bSum = 0;

            for (let y = y0; y < y1; y++) {
                const rowOffset = y * width;
                for (let x = x0; x < x1; x++) {
                    const idx = (rowOffset + x) * 4;
                    let r = data[idx];
                    let g = data[idx + 1];
                    let b = data[idx + 2];
                    const a = data[idx + 3];
                    if (a !== 255) {
                        r = flattenChannel(r, a);
                        g = flattenChannel(g, a);
                        b = flattenChannel(b, a);
                    }
                    if (isGray) {
                        r = g = b = grayValue(r, g, b);
                    }
                    rSum += r;
                    gSum += g;
                    bSum += b;
                }
            }

            const count = (y1 - y0) * (x1 - x0);
            let r = Math.floor(rSum / count);
            let g = Math.floor(gSum / count);
            let b = Math.floor(bSum / count);

            if (isBw) {
                r = thresholdChannel(r);
                g = thresholdChannel(g);
                b = thresholdChannel(b);
            } else {
                r = quantizeChannel(r, colorLevels);
                g = quantizeChannel(g, colorLevels);
                b = quantizeChannel(b, colorLevels);
            }

            band[bx * 3] = r;
            band[bx * 3 + 1] = g;
            band[bx * 3 + 2] = b;
        }

        return band;
    }

    /** Run-length-encode one block row into { x, width, color } runs. */
    function rowRuns(band, starts, ends) {
        const runs = [];
        const count = starts.length;
        let start = 0;

        while (start < count) {
            let end = start + 1;
            while (
                end < count &&
                band[end * 3] === band[start * 3] &&
                band[end * 3 + 1] === band[start * 3 + 1] &&
                band[end * 3 + 2] === band[start * 3 + 2]
            ) {
                end++;
            }
            runs.push({
                x: starts[start],
                width: ends[end - 1] - starts[start],
                color:
                    "rgb(" +
                    band[start * 3] + "," +
                    band[start * 3 + 1] + "," +
                    band[start * 3 + 2] +
                    ")",
            });
            start = end;
        }

        return runs;
    }

    /**
     * Convert RGBA pixels (e.g. ImageData.data) into an SVG string.
     *
     * Pass the source pixels untouched: transparency and the luma filter are
     * handled here (step 0). `options.headerComments` replaces the header
     * comments; `options.onProgress(fraction)` is called with 0..1 as bands
     * are processed. Throws RangeError on invalid settings, and a RangeError
     * with `code === "TOO_COMPLEX"` above MAX_BLOCKS.
     */
    function createSVG(data, width, height, colorLevels, detailLevel, conversionType, options) {
        if (VALID_CONVERSION_TYPES.indexOf(conversionType) === -1) {
            throw new RangeError(
                "conversionType must be one of " + VALID_CONVERSION_TYPES.join(", ") +
                ", got " + conversionType
            );
        }
        if (!(colorLevels >= MIN_COLOR_LEVELS && colorLevels <= MAX_COLOR_LEVELS)) {
            throw new RangeError(
                "colorLevels must be between " + MIN_COLOR_LEVELS + " and " +
                MAX_COLOR_LEVELS + ", got " + colorLevels
            );
        }
        if (!(detailLevel >= MIN_DETAIL_LEVEL && detailLevel <= MAX_DETAIL_LEVEL)) {
            throw new RangeError(
                "detailLevel must be between " + MIN_DETAIL_LEVEL + " and " +
                MAX_DETAIL_LEVEL + ", got " + detailLevel
            );
        }
        if (!(width > 0 && height > 0)) {
            throw new RangeError("image must not be empty, got " + width + "x" + height);
        }
        const blocks = blockCount(width, height, detailLevel);
        if (blocks > MAX_BLOCKS) {
            const err = new RangeError(
                "output would contain " + blocks + " blocks, more than the limit of " +
                MAX_BLOCKS
            );
            err.code = "TOO_COMPLEX";
            throw err;
        }

        const opts = options || {};
        const headerComments = opts.headerComments || DEFAULT_HEADER_COMMENTS;
        const onProgress = opts.onProgress || null;
        const blockSize = MAX_BLOCK_SIZE + 1 - detailLevel;
        const cols = blockBounds(width, blockSize);
        const bands = blockBounds(height, blockSize);
        const isBw = conversionType === "bw";
        const isGray = conversionType !== "color";
        const bandCount = bands.starts.length;
        const progressEvery = Math.max(1, Math.floor(bandCount / PROGRESS_UPDATES));

        // color -> rectangles, in first-appearance order (Map preserves insertion).
        const groups = new Map();
        // "x|width|color" -> rectangle still open from the previous band.
        let openRects = new Map();

        for (let by = 0; by < bandCount; by++) {
            if (onProgress && by % progressEvery === 0) {
                onProgress(by / bandCount);
            }
            const y0 = bands.starts[by];
            const bandHeight = bands.ends[by] - y0;
            const band = averageBand(
                data, width, y0, bands.ends[by], cols.starts, cols.ends,
                colorLevels, isBw, isGray
            );
            const runs = rowRuns(band, cols.starts, cols.ends);
            const nextOpen = new Map();

            for (const run of runs) {
                const key = run.x + "|" + run.width + "|" + run.color;
                let rect = openRects.get(key);
                if (rect && rect.y + rect.h === y0) {
                    rect.h += bandHeight;
                } else {
                    rect = { x: run.x, y: y0, w: run.width, h: bandHeight };
                    let bucket = groups.get(run.color);
                    if (!bucket) {
                        bucket = [];
                        groups.set(run.color, bucket);
                    }
                    bucket.push(rect);
                }
                nextOpen.set(key, rect);
            }

            openRects = nextOpen;
        }

        if (onProgress) {
            onProgress(1);
        }
        return emitSVG(width, height, groups, headerComments);
    }

    function emitSVG(width, height, groups, headerComments) {
        const parts = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' +
                width + " " + height + '" width="' + width + '" height="' + height +
                '" shape-rendering="crispEdges">',
        ];
        for (const comment of headerComments) {
            parts.push("  <!-- " + comment + " -->");
        }

        for (const [color, rects] of groups) {
            parts.push('  <g fill="' + color + '">');
            for (const rect of rects) {
                parts.push(
                    '    <rect x="' + rect.x + '" y="' + rect.y +
                    '" width="' + rect.w + '" height="' + rect.h + '"/>'
                );
            }
            parts.push("  </g>");
        }

        parts.push("</svg>");
        return parts.join("\n");
    }

    return {
        createSVG: createSVG,
        blockCount: blockCount,
        flattenChannel: flattenChannel,
        grayValue: grayValue,
        quantizeChannel: quantizeChannel,
        thresholdChannel: thresholdChannel,
        BW_THRESHOLD: BW_THRESHOLD,
        MAX_BLOCKS: MAX_BLOCKS,
        MAX_BLOCK_SIZE: MAX_BLOCK_SIZE,
        MIN_DETAIL_LEVEL: MIN_DETAIL_LEVEL,
        MAX_DETAIL_LEVEL: MAX_DETAIL_LEVEL,
        DEFAULT_DETAIL_LEVEL: DEFAULT_DETAIL_LEVEL,
        MIN_COLOR_LEVELS: MIN_COLOR_LEVELS,
        MAX_COLOR_LEVELS: MAX_COLOR_LEVELS,
        DEFAULT_COLOR_LEVELS: DEFAULT_COLOR_LEVELS,
        VALID_CONVERSION_TYPES: VALID_CONVERSION_TYPES,
        DEFAULT_HEADER_COMMENTS: DEFAULT_HEADER_COMMENTS,
    };
});
