/**
 * svg-core.js
 *
 * JavaScript port of the canonical conversion algorithm that lives in
 * `svg_core.py`. The two MUST produce byte-identical output: `tests/fixtures/`
 * holds golden files that both the pytest and the node:test suites assert
 * against, so any drift between them fails CI.
 *
 * Algorithm (canonical — mirrored exactly in svg_core.py):
 *   1. Split the image into blocks of `blockSize = MAX_BLOCK_SIZE + 1 - detailLevel`.
 *   2. Average pixel colors inside each block (integer floor division).
 *   3. Posterize each channel to `colorLevels` values, range-preserving:
 *      0 stays 0 and 255 stays 255. In "bw" mode each channel is instead
 *      re-thresholded at BW_THRESHOLD so averaging a block of black and white
 *      pixels cannot leak grays into a mode that is meant to be binary.
 *   4. Run-length-encode each block row horizontally.
 *   5. Merge each run with the run directly above it when color, x and width
 *      match, producing rectangles merged in BOTH axes.
 *   6. Emit <g fill="..."> groups in first-appearance order.
 *
 * All arithmetic in steps 2-3 is integer-only over non-negative operands, so
 * `Math.floor(a / b)` here and `a // b` in Python agree exactly.
 *
 * Exposed as a UMD-ish module: works in a regular <script> tag
 * (`globalThis.SvgCore`), inside a Web Worker (`self.SvgCore`), and under
 * `require()` in Node.
 */
(function (root, factory) {
    "use strict";
    const api = factory();
    root.SvgCore = api;
    if (typeof module !== "undefined" && module.exports) {
        module.exports = api;
    }
})(typeof self !== "undefined" ? self : globalThis, function () {
    "use strict";

    const VALID_CONVERSION_TYPES = Object.freeze(["color", "bw", "grayscale"]);

    /** Grayscale value at or above which a pixel becomes white in "bw" mode. */
    const BW_THRESHOLD = 128;

    /**
     * Largest block edge, reached at detailLevel === MIN_DETAIL_LEVEL.
     * blockSize = MAX_BLOCK_SIZE + 1 - detailLevel, so detail 1 -> 10px blocks
     * (coarse) and detail 10 -> 1px blocks (every pixel kept).
     */
    const MAX_BLOCK_SIZE = 10;

    const MIN_DETAIL_LEVEL = 1;
    const MAX_DETAIL_LEVEL = 10;
    const DEFAULT_DETAIL_LEVEL = 5;

    /**
     * Number of distinct values kept per RGB channel. The resulting palette
     * holds colorLevels ** 3 colors (2 -> 8 colors, 6 -> 216 colors).
     */
    const MIN_COLOR_LEVELS = 2;
    const MAX_COLOR_LEVELS = 6;
    const DEFAULT_COLOR_LEVELS = 3;

    const DEFAULT_HEADER_COMMENTS = Object.freeze([
        "Generated by محول SVG",
        "تطوير: عبدالكريم العبود | abo.saleh.g@gmail.com",
        "© 2024 محول SVG - All Rights Reserved",
    ]);

    /**
     * Posterize one 0-255 channel to `colorLevels` evenly spaced values.
     *
     * Unlike naive `(v / step | 0) * step` truncation this is range-preserving:
     * 0 maps to 0 and 255 maps to 255 for every level count, so whites stay
     * white instead of collapsing to mid-gray. Integer half-up rounding keeps
     * it identical to the Python implementation.
     */
    function quantizeChannel(value, colorLevels) {
        const steps = colorLevels - 1;
        // round(value * steps / 255), half-up
        const index = Math.floor((value * steps * 2 + 255) / 510);
        // round(index * 255 / steps), half-up
        return Math.floor((index * 510 + steps) / (steps * 2));
    }

    /** Snap one channel back to pure black or white for "bw" mode. */
    function thresholdChannel(value) {
        return value >= BW_THRESHOLD ? 255 : 0;
    }

    /** Convert RGB pixels in place to grayscale or pure black/white. */
    function applyGrayscaleFilter(data, conversionType) {
        if (conversionType !== "bw" && conversionType !== "grayscale") {
            return;
        }
        for (let i = 0; i < data.length; i += 4) {
            const gray = Math.round(
                0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2]
            );
            if (conversionType === "bw") {
                const value = gray >= BW_THRESHOLD ? 255 : 0;
                data[i] = data[i + 1] = data[i + 2] = value;
            } else {
                data[i] = data[i + 1] = data[i + 2] = gray;
            }
        }
    }

    /** Return { starts, ends } of the blocks covering `size` pixels. */
    function blockBounds(size, blockSize) {
        const starts = [];
        const ends = [];
        for (let start = 0; start < size; start += blockSize) {
            starts.push(start);
            ends.push(Math.min(start + blockSize, size));
        }
        return { starts: starts, ends: ends };
    }

    /**
     * Average one block row into a flat [r, g, b, r, g, b, ...] array,
     * posterizing when requested.
     */
    function averageBand(data, width, y0, y1, starts, ends, colorLevels, isBw) {
        const bandWidth = starts.length;
        const band = new Uint8Array(bandWidth * 3);

        for (let bx = 0; bx < bandWidth; bx++) {
            const x0 = starts[bx];
            const x1 = ends[bx];
            let rSum = 0;
            let gSum = 0;
            let bSum = 0;

            for (let y = y0; y < y1; y++) {
                const rowOffset = y * width;
                for (let x = x0; x < x1; x++) {
                    const idx = (rowOffset + x) * 4;
                    rSum += data[idx];
                    gSum += data[idx + 1];
                    bSum += data[idx + 2];
                }
            }

            const count = (y1 - y0) * (x1 - x0);
            let r = Math.floor(rSum / count);
            let g = Math.floor(gSum / count);
            let b = Math.floor(bSum / count);

            if (isBw) {
                r = thresholdChannel(r);
                g = thresholdChannel(g);
                b = thresholdChannel(b);
            } else {
                r = quantizeChannel(r, colorLevels);
                g = quantizeChannel(g, colorLevels);
                b = quantizeChannel(b, colorLevels);
            }

            band[bx * 3] = r;
            band[bx * 3 + 1] = g;
            band[bx * 3 + 2] = b;
        }

        return band;
    }

    /** Run-length-encode one block row into { x, width, color } runs. */
    function rowRuns(band, starts, ends) {
        const runs = [];
        const count = starts.length;
        let start = 0;

        while (start < count) {
            let end = start + 1;
            while (
                end < count &&
                band[end * 3] === band[start * 3] &&
                band[end * 3 + 1] === band[start * 3 + 1] &&
                band[end * 3 + 2] === band[start * 3 + 2]
            ) {
                end++;
            }
            runs.push({
                x: starts[start],
                width: ends[end - 1] - starts[start],
                color:
                    "rgb(" +
                    band[start * 3] + "," +
                    band[start * 3 + 1] + "," +
                    band[start * 3 + 2] +
                    ")",
            });
            start = end;
        }

        return runs;
    }

    function createSVG(data, width, height, colorLevels, detailLevel, conversionType, options) {
        if (VALID_CONVERSION_TYPES.indexOf(conversionType) === -1) {
            throw new RangeError(
                "conversionType must be one of " + VALID_CONVERSION_TYPES.join(", ") +
                ", got " + conversionType
            );
        }
        if (!(colorLevels >= MIN_COLOR_LEVELS && colorLevels <= MAX_COLOR_LEVELS)) {
            throw new RangeError(
                "colorLevels must be between " + MIN_COLOR_LEVELS + " and " +
                MAX_COLOR_LEVELS + ", got " + colorLevels
            );
        }
        if (!(detailLevel >= MIN_DETAIL_LEVEL && detailLevel <= MAX_DETAIL_LEVEL)) {
            throw new RangeError(
                "detailLevel must be between " + MIN_DETAIL_LEVEL + " and " +
                MAX_DETAIL_LEVEL + ", got " + detailLevel
            );
        }
        if (!(width > 0 && height > 0)) {
            throw new RangeError("image must not be empty, got " + width + "x" + height);
        }

        const opts = options || {};
        const headerComments = opts.headerComments || DEFAULT_HEADER_COMMENTS;
        const blockSize = MAX_BLOCK_SIZE + 1 - detailLevel;
        const cols = blockBounds(width, blockSize);
        const bands = blockBounds(height, blockSize);
        const isBw = conversionType === "bw";

        // color -> rectangles, in first-appearance order (Map preserves insertion).
        const groups = new Map();
        // "x|width|color" -> rectangle still open from the previous band.
        let openRects = new Map();

        for (let by = 0; by < bands.starts.length; by++) {
            const y0 = bands.starts[by];
            const bandHeight = bands.ends[by] - y0;
            const band = averageBand(
                data, width, y0, bands.ends[by], cols.starts, cols.ends, colorLevels, isBw
            );
            const runs = rowRuns(band, cols.starts, cols.ends);
            const nextOpen = new Map();

            for (const run of runs) {
                const key = run.x + "|" + run.width + "|" + run.color;
                let rect = openRects.get(key);
                if (rect && rect.y + rect.h === y0) {
                    rect.h += bandHeight;
                } else {
                    rect = { x: run.x, y: y0, w: run.width, h: bandHeight };
                    let bucket = groups.get(run.color);
                    if (!bucket) {
                        bucket = [];
                        groups.set(run.color, bucket);
                    }
                    bucket.push(rect);
                }
                nextOpen.set(key, rect);
            }

            openRects = nextOpen;
        }

        return emitSVG(width, height, groups, headerComments);
    }

    function emitSVG(width, height, groups, headerComments) {
        const parts = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' +
                width + " " + height + '" width="' + width + '" height="' + height +
                '" shape-rendering="crispEdges">',
        ];
        for (const comment of headerComments) {
            parts.push("  <!-- " + comment + " -->");
        }

        for (const [color, rects] of groups) {
            parts.push('  <g fill="' + color + '">');
            for (const rect of rects) {
                parts.push(
                    '    <rect x="' + rect.x + '" y="' + rect.y +
                    '" width="' + rect.w + '" height="' + rect.h + '"/>'
                );
            }
            parts.push("  </g>");
        }

        parts.push("</svg>");
        return parts.join("\n");
    }

    return {
        createSVG: createSVG,
        applyGrayscaleFilter: applyGrayscaleFilter,
        quantizeChannel: quantizeChannel,
        thresholdChannel: thresholdChannel,
        BW_THRESHOLD: BW_THRESHOLD,
        MAX_BLOCK_SIZE: MAX_BLOCK_SIZE,
        MIN_DETAIL_LEVEL: MIN_DETAIL_LEVEL,
        MAX_DETAIL_LEVEL: MAX_DETAIL_LEVEL,
        DEFAULT_DETAIL_LEVEL: DEFAULT_DETAIL_LEVEL,
        MIN_COLOR_LEVELS: MIN_COLOR_LEVELS,
        MAX_COLOR_LEVELS: MAX_COLOR_LEVELS,
        DEFAULT_COLOR_LEVELS: DEFAULT_COLOR_LEVELS,
        VALID_CONVERSION_TYPES: VALID_CONVERSION_TYPES,
        DEFAULT_HEADER_COMMENTS: DEFAULT_HEADER_COMMENTS,
    };
});
