/**
 * svg-core.js
 *
 * Shared bitmap-to-SVG conversion logic for the web app.
 * Mirrors the Python implementation in `svg_core.py` so both stay in sync.
 *
 * Algorithm:
 *   1. Split the image into blocks of size `max(1, 11 - detailLevel)`.
 *   2. Average pixel colors inside each block.
 *   3. Quantize colors (cube-root posterization) unless conversionType === "bw".
 *   4. Group blocks by color, sort row-then-column, and merge horizontally
 *      adjacent rectangles of the same color and height.
 *   5. Emit <g fill="..."> groups with merged <rect> children.
 *
 * Exposed as a UMD-ish module: works in both a regular <script> tag (attaches
 * to `globalThis.SvgCore`) and inside a Web Worker (`self.SvgCore`).
 */
(function (root, factory) {
    "use strict";
    const api = factory();
    root.SvgCore = api;
    if (typeof module !== "undefined" && module.exports) {
        module.exports = api;
    }
})(typeof self !== "undefined" ? self : globalThis, function () {
    "use strict";

    const DEFAULT_HEADER_COMMENTS = Object.freeze([
        "Generated by محول SVG",
        "تطوير: عبدالكريم العبود | abo.saleh.g@gmail.com",
        "© 2024 محول SVG - All Rights Reserved",
    ]);

    function applyGrayscaleFilter(data, conversionType) {
        if (conversionType !== "bw" && conversionType !== "grayscale") {
            return;
        }
        for (let i = 0; i < data.length; i += 4) {
            const gray = Math.round(
                0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2]
            );
            if (conversionType === "bw") {
                const val = gray > 128 ? 255 : 0;
                data[i] = data[i + 1] = data[i + 2] = val;
            } else {
                data[i] = data[i + 1] = data[i + 2] = gray;
            }
        }
    }

    function createSVG(data, width, height, numColors, detailLevel, conversionType, options) {
        const opts = options || {};
        const headerComments = opts.headerComments || DEFAULT_HEADER_COMMENTS;
        const blockSize = Math.max(1, 11 - detailLevel);
        const colorGroups = Object.create(null);

        let step = 0;
        if (conversionType !== "bw") {
            const levels = Math.max(2, Math.floor(Math.cbrt(numColors)));
            step = Math.max(1, Math.floor(256 / levels));
        }

        for (let y = 0; y < height; y += blockSize) {
            for (let x = 0; x < width; x += blockSize) {
                let r = 0, g = 0, b = 0, count = 0;
                const maxDy = Math.min(blockSize, height - y);
                const maxDx = Math.min(blockSize, width - x);

                for (let dy = 0; dy < maxDy; dy++) {
                    const rowOffset = (y + dy) * width;
                    for (let dx = 0; dx < maxDx; dx++) {
                        const idx = (rowOffset + (x + dx)) * 4;
                        r += data[idx];
                        g += data[idx + 1];
                        b += data[idx + 2];
                        count++;
                    }
                }

                r = (r / count) | 0;
                g = (g / count) | 0;
                b = (b / count) | 0;

                if (conversionType !== "bw") {
                    r = Math.min(255, ((r / step) | 0) * step);
                    g = Math.min(255, ((g / step) | 0) * step);
                    b = Math.min(255, ((b / step) | 0) * step);
                }

                const color = "rgb(" + r + "," + g + "," + b + ")";
                const rectW = maxDx;
                const rectH = maxDy;

                if (!colorGroups[color]) {
                    colorGroups[color] = [];
                }
                colorGroups[color].push({ x: x, y: y, w: rectW, h: rectH });
            }
        }

        return emitSVG(width, height, colorGroups, headerComments);
    }

    function emitSVG(width, height, colorGroups, headerComments) {
        const parts = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' +
                width + ' ' + height + '" width="' + width + '" height="' + height + '">',
        ];
        for (const c of headerComments) {
            parts.push("  <!-- " + c + " -->");
        }

        for (const color in colorGroups) {
            const rects = colorGroups[color];
            rects.sort((a, b) => a.y - b.y || a.x - b.x);

            const merged = [];
            for (const rect of rects) {
                const last = merged[merged.length - 1];
                if (last && last.y === rect.y && last.h === rect.h && last.x + last.w === rect.x) {
                    last.w += rect.w;
                } else {
                    merged.push({ x: rect.x, y: rect.y, w: rect.w, h: rect.h });
                }
            }

            parts.push('  <g fill="' + color + '">');
            for (const rect of merged) {
                parts.push(
                    '    <rect x="' + rect.x + '" y="' + rect.y +
                    '" width="' + rect.w + '" height="' + rect.h + '"/>'
                );
            }
            parts.push("  </g>");
        }

        parts.push("</svg>");
        return parts.join("\n");
    }

    return {
        createSVG: createSVG,
        applyGrayscaleFilter: applyGrayscaleFilter,
        DEFAULT_HEADER_COMMENTS: DEFAULT_HEADER_COMMENTS,
    };
});
