#!/usr/bin/env python3
"""svg_core - منطق تحويل الصور إلى SVG (مشترك بين تطبيق سطح المكتب والويب).

This module owns the canonical bitmap-to-SVG conversion algorithm. The
JavaScript port lives in ``svg-core.js`` and MUST stay byte-for-byte
identical; ``tests/fixtures/`` holds golden files that both test suites
assert against, so any drift between the two fails CI.

Algorithm (canonical — mirrored exactly in svg-core.js):
    1. Split the image into blocks of ``block_size = MAX_BLOCK_SIZE + 1 - detail_level``.
    2. Average pixel colors inside each block (integer floor division).
    3. Posterize each channel to ``color_levels`` values, range-preserving:
       0 stays 0 and 255 stays 255. In ``"bw"`` mode each channel is instead
       re-thresholded at ``BW_THRESHOLD`` so averaging a block of black and
       white pixels cannot leak grays into a mode that is meant to be binary.
    4. Run-length-encode each block row horizontally.
    5. Merge each run with the run directly above it when color, x and width
       match, producing rectangles merged in BOTH axes.
    6. Emit ``<g fill="...">`` groups in first-appearance order.

All arithmetic in steps 2-3 is integer-only and uses non-negative operands, so
Python's ``//`` and JavaScript's ``Math.floor(a / b)`` agree exactly.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence

try:  # NumPy is optional: it only accelerates step 2, never changes the output.
    import numpy as np

    _HAS_NUMPY = True
except ImportError:  # pragma: no cover - depends on environment
    np = None  # type: ignore[assignment]
    _HAS_NUMPY = False

__all__ = [
    "BW_THRESHOLD",
    "ConversionType",
    "DEFAULT_COLOR_LEVELS",
    "DEFAULT_DETAIL_LEVEL",
    "DEFAULT_HEADER_COMMENTS",
    "MAX_BLOCK_SIZE",
    "MAX_COLOR_LEVELS",
    "MAX_DETAIL_LEVEL",
    "MIN_COLOR_LEVELS",
    "MIN_DETAIL_LEVEL",
    "VALID_CONVERSION_TYPES",
    "create_svg",
    "numpy_available",
    "quantize_channel",
    "threshold_channel",
]

ConversionType = str  # one of: "color", "bw", "grayscale"

VALID_CONVERSION_TYPES = ("color", "bw", "grayscale")

#: Grayscale value at or above which a pixel becomes white in "bw" mode.
BW_THRESHOLD = 128

#: Largest block edge, reached at ``detail_level == MIN_DETAIL_LEVEL``.
#: ``block_size = MAX_BLOCK_SIZE + 1 - detail_level``, so detail 1 -> 10px
#: blocks (coarse) and detail 10 -> 1px blocks (every pixel kept).
MAX_BLOCK_SIZE = 10

MIN_DETAIL_LEVEL = 1
MAX_DETAIL_LEVEL = 10
DEFAULT_DETAIL_LEVEL = 5

#: Number of distinct values kept per RGB channel. The resulting palette holds
#: ``color_levels ** 3`` colors (2 -> 8 colors, 6 -> 216 colors).
MIN_COLOR_LEVELS = 2
MAX_COLOR_LEVELS = 6
DEFAULT_COLOR_LEVELS = 3

DEFAULT_HEADER_COMMENTS: tuple[str, ...] = (
    "Generated by محول SVG",
    "تطوير: عبدالكريم العبود | abo.saleh.g@gmail.com",
    "© 2024 محول SVG - All Rights Reserved",
)


def numpy_available() -> bool:
    """Whether the NumPy fast path for block averaging is usable."""
    return _HAS_NUMPY


def quantize_channel(value: int, color_levels: int) -> int:
    """Posterize one 0-255 channel to ``color_levels`` evenly spaced values.

    Unlike naive ``(v // step) * step`` truncation, this is range-preserving:
    ``0`` maps to ``0`` and ``255`` maps to ``255`` for every level count, so
    whites stay white instead of collapsing to mid-gray.

    Written with integer half-up rounding (no floats) so the JavaScript port
    produces identical bytes.
    """
    steps = color_levels - 1
    # round(value * steps / 255), half-up
    index = (value * steps * 2 + 255) // 510
    # round(index * 255 / steps), half-up
    return (index * 510 + steps) // (steps * 2)


def _block_bounds(size: int, block_size: int) -> tuple[list[int], list[int]]:
    """Return (starts, ends) of the blocks covering ``size`` pixels."""
    starts = list(range(0, size, block_size))
    ends = [min(start + block_size, size) for start in starts]
    return starts, ends


def _grid_python(
    pixels,
    starts_x: Sequence[int],
    ends_x: Sequence[int],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
) -> list[list[tuple[int, int, int]]]:
    """Average each block with plain Python. Reference implementation."""
    grid: list[list[tuple[int, int, int]]] = []
    for y0, y1 in zip(starts_y, ends_y):
        row: list[tuple[int, int, int]] = []
        for x0, x1 in zip(starts_x, ends_x):
            r_sum = g_sum = b_sum = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    pixel = pixels[x, y]
                    r_sum += pixel[0]
                    g_sum += pixel[1]
                    b_sum += pixel[2]
            count = (y1 - y0) * (x1 - x0)
            row.append((r_sum // count, g_sum // count, b_sum // count))
        grid.append(row)
    return grid


def _grid_numpy(
    img,
    starts_x: Sequence[int],
    ends_x: Sequence[int],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
):
    """Average each block with NumPy — same integer result, much faster.

    Measured end-to-end on 1200x900 images: 3-6x on high-noise input, 6-12x on
    photographic or flat artwork. (Block averaging is what this removes; the
    run-length and merge passes stay in Python and dominate on noisy input.)


    ``np.add.reduceat`` sums the half-open segments ``[starts[i], starts[i+1])``
    and runs the final segment to the end of the axis, which is exactly the
    block layout including the partial blocks at the right/bottom edges.
    Summing with ``dtype=uint32`` keeps the source array as uint8: a block holds
    at most ``MAX_BLOCK_SIZE ** 2 * 255 = 25500``, so it cannot overflow.
    """
    arr = np.asarray(img, dtype=np.uint8)
    if arr.ndim != 3 or arr.shape[2] < 3:  # pragma: no cover - guarded by caller
        raise ValueError("expected an RGB image array")
    arr = arr[:, :, :3]

    row_sums = np.add.reduceat(arr, np.asarray(starts_y), axis=0, dtype=np.uint32)
    block_sums = np.add.reduceat(row_sums, np.asarray(starts_x), axis=1, dtype=np.uint32)

    heights = np.asarray(ends_y, dtype=np.uint32) - np.asarray(starts_y, dtype=np.uint32)
    widths = np.asarray(ends_x, dtype=np.uint32) - np.asarray(starts_x, dtype=np.uint32)
    counts = heights[:, None] * widths[None, :]

    return block_sums // counts[:, :, None]


def threshold_channel(value: int) -> int:
    """Snap one channel back to pure black or white for ``"bw"`` mode."""
    return 255 if value >= BW_THRESHOLD else 0


def _posterize_grid_numpy(grid, conversion_type: ConversionType, color_levels: int):
    """Vectorized step 3 over a whole block grid."""
    if conversion_type == "bw":
        return np.where(grid >= BW_THRESHOLD, 255, 0)
    steps = color_levels - 1
    index = (grid * (steps * 2) + 255) // 510
    return (index * 510 + steps) // (steps * 2)


def _row_runs(
    row: Sequence[Sequence[int]],
    starts_x: Sequence[int],
    ends_x: Sequence[int],
) -> list[tuple[int, int, tuple[int, int, int]]]:
    """Run-length-encode one block row into (x, width, rgb) runs."""
    runs: list[tuple[int, int, tuple[int, int, int]]] = []
    count = len(row)
    start = 0
    while start < count:
        end = start + 1
        while (
            end < count
            and row[end][0] == row[start][0]
            and row[end][1] == row[start][1]
            and row[end][2] == row[start][2]
        ):
            end += 1
        color = row[start]
        runs.append(
            (
                starts_x[start],
                ends_x[end - 1] - starts_x[start],
                (int(color[0]), int(color[1]), int(color[2])),
            )
        )
        start = end
    return runs


def _merge_vertically(
    rows: Iterable[list[tuple[int, int, tuple[int, int, int]]]],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
) -> dict[str, list[list[int]]]:
    """Merge each run into the run above it, then group rectangles by color.

    Groups keep first-appearance order and rectangles keep (y, x) order, which
    makes the output byte-stable across runs and across languages.
    """
    groups: dict[str, list[list[int]]] = {}
    open_rects: dict[tuple[int, int, str], list[int]] = {}

    for band, runs in enumerate(rows):
        y0 = starts_y[band]
        height = ends_y[band] - y0
        next_open: dict[tuple[int, int, str], list[int]] = {}

        for x, width, rgb in runs:
            color = f"rgb({rgb[0]},{rgb[1]},{rgb[2]})"
            key = (x, width, color)
            rect = open_rects.get(key)
            if rect is not None and rect[1] + rect[3] == y0:
                rect[3] += height
            else:
                rect = [x, y0, width, height]
                groups.setdefault(color, []).append(rect)
            next_open[key] = rect

        open_rects = next_open

    return groups


def _emit_svg(
    width: int,
    height: int,
    groups: dict[str, list[list[int]]],
    header_comments: Iterable[str],
) -> str:
    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}" width="{width}" height="{height}" '
            f'shape-rendering="crispEdges">'
        ),
    ]
    for comment in header_comments:
        lines.append(f"  <!-- {comment} -->")

    for color, rects in groups.items():
        lines.append(f'  <g fill="{color}">')
        for x, y, rect_w, rect_h in rects:
            lines.append(f'    <rect x="{x}" y="{y}" width="{rect_w}" height="{rect_h}"/>')
        lines.append("  </g>")

    lines.append("</svg>")
    return "\n".join(lines)


def create_svg(
    img,
    conversion_type: ConversionType,
    color_levels: int = DEFAULT_COLOR_LEVELS,
    detail_level: int = DEFAULT_DETAIL_LEVEL,
    header_comments: Iterable[str] = DEFAULT_HEADER_COMMENTS,
) -> str:
    """Convert a PIL Image into an SVG string.

    Args:
        img: A PIL ``Image``. Converted to ``RGB`` automatically if needed.
        conversion_type: ``"color"``, ``"bw"``, or ``"grayscale"``.
        color_levels: Values kept per RGB channel (2-6); the palette holds
            ``color_levels ** 3`` colors. Ignored for ``"bw"``.
        detail_level: 1-10; higher = smaller blocks = more detail.
        header_comments: Comments injected at the top of the SVG.

    Returns:
        A UTF-8 SVG document as a string.

    Raises:
        ValueError: on an unknown ``conversion_type``, an out-of-range
            ``color_levels`` / ``detail_level``, or an empty image.
    """
    if conversion_type not in VALID_CONVERSION_TYPES:
        raise ValueError(
            f"conversion_type must be one of {VALID_CONVERSION_TYPES}, got {conversion_type!r}"
        )
    if not MIN_COLOR_LEVELS <= color_levels <= MAX_COLOR_LEVELS:
        raise ValueError(
            f"color_levels must be between {MIN_COLOR_LEVELS} and {MAX_COLOR_LEVELS}, "
            f"got {color_levels!r}"
        )
    if not MIN_DETAIL_LEVEL <= detail_level <= MAX_DETAIL_LEVEL:
        raise ValueError(
            f"detail_level must be between {MIN_DETAIL_LEVEL} and {MAX_DETAIL_LEVEL}, "
            f"got {detail_level!r}"
        )

    if img.mode != "RGB":
        img = img.convert("RGB")

    width, height = img.size
    if width <= 0 or height <= 0:
        raise ValueError(f"image must not be empty, got {width}x{height}")

    block_size = MAX_BLOCK_SIZE + 1 - detail_level
    starts_x, ends_x = _block_bounds(width, block_size)
    starts_y, ends_y = _block_bounds(height, block_size)

    if conversion_type == "bw":

        def posterize(value: int) -> int:
            return threshold_channel(value)
    else:

        def posterize(value: int) -> int:
            return quantize_channel(value, color_levels)

    if _HAS_NUMPY:
        grid = _grid_numpy(img, starts_x, ends_x, starts_y, ends_y)
        grid = _posterize_grid_numpy(grid, conversion_type, color_levels)
        rows = (_row_runs(band.tolist(), starts_x, ends_x) for band in grid)
    else:
        pixels = img.load()
        py_grid = [
            [(posterize(r), posterize(g), posterize(b)) for r, g, b in band]
            for band in _grid_python(pixels, starts_x, ends_x, starts_y, ends_y)
        ]
        rows = (_row_runs(band, starts_x, ends_x) for band in py_grid)

    groups = _merge_vertically(rows, starts_y, ends_y)
    return _emit_svg(width, height, groups, header_comments)
