#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
svg_core - منطق تحويل الصور إلى SVG (مشترك بين تطبيق سطح المكتب وأي تطبيق آخر مستقبلاً).

This module centralizes the bitmap-to-SVG conversion algorithm previously
duplicated inside ``svg_converter.py`` and ``index.html``.

Algorithm:
    1. Split image into blocks of ``block_size = max(1, 11 - detail_level)``.
    2. Average pixel colors inside each block.
    3. Quantize colors (cube-root posterization) unless ``conversion_type == "bw"``.
    4. Group blocks by color, sort row-then-column, and merge horizontally
       adjacent rectangles of the same color and height.
    5. Emit ``<g fill="...">`` groups with merged ``<rect>`` children.

Exposes a single public function :func:`create_svg` whose signature mirrors the
JS ``createSVG`` helper in ``svg-core.js`` so the two implementations stay in
sync.
"""

from __future__ import annotations

from typing import Iterable, List, Tuple

__all__ = ["create_svg", "ConversionType", "DEFAULT_HEADER_COMMENTS"]

ConversionType = str  # one of: "color", "bw", "grayscale"

DEFAULT_HEADER_COMMENTS: Tuple[str, ...] = (
    "Generated by محول SVG",
    "تطوير: عبدالكريم العبود | abo.saleh.g@gmail.com",
    "© 2024 محول SVG - All Rights Reserved",
)


def _quantize_channel(value: int, step: int) -> int:
    return min(255, (value // step) * step)


def _iter_blocks(
    pixels, width: int, height: int, block_size: int
) -> Iterable[Tuple[int, int, int, int, int]]:
    """Yield (x, y, avg_r, avg_g, avg_b) for each block."""
    for y in range(0, height, block_size):
        for x in range(0, width, block_size):
            r_sum = g_sum = b_sum = count = 0
            for dy in range(min(block_size, height - y)):
                for dx in range(min(block_size, width - x)):
                    px = pixels[x + dx, y + dy]
                    r_sum += px[0]
                    g_sum += px[1]
                    b_sum += px[2]
                    count += 1
            yield x, y, r_sum // count, g_sum // count, b_sum // count


def create_svg(
    img,
    conversion_type: ConversionType,
    num_colors: int = 16,
    detail_level: int = 5,
    header_comments: Iterable[str] = DEFAULT_HEADER_COMMENTS,
) -> str:
    """Convert a PIL Image (RGB mode) into an SVG string.

    Args:
        img: A PIL ``Image`` instance in ``RGB`` mode.
        conversion_type: ``"color"``, ``"bw"``, or ``"grayscale"``.
        num_colors: Target palette size when quantizing (2-64). Ignored for ``"bw"``.
        detail_level: 1-10; higher = smaller block size = more detail.
        header_comments: Comments injected at the top of the SVG.

    Returns:
        A UTF-8 SVG document as a string.
    """
    width, height = img.size
    block_size = max(1, 11 - detail_level)
    pixels = img.load()

    color_groups: dict[str, List[Tuple[int, int, int, int]]] = {}

    if conversion_type != "bw":
        levels = max(2, int(num_colors ** (1 / 3)))
        step = max(1, 256 // levels)
    else:
        step = 0  # unused

    for x, y, r, g, b in _iter_blocks(pixels, width, height, block_size):
        if conversion_type != "bw":
            r = _quantize_channel(r, step)
            g = _quantize_channel(g, step)
            b = _quantize_channel(b, step)

        color = f"rgb({r},{g},{b})"
        rect_w = min(block_size, width - x)
        rect_h = min(block_size, height - y)
        color_groups.setdefault(color, []).append((x, y, rect_w, rect_h))

    return _emit_svg(width, height, color_groups, header_comments)


def _emit_svg(
    width: int,
    height: int,
    color_groups: dict[str, List[Tuple[int, int, int, int]]],
    header_comments: Iterable[str],
) -> str:
    lines: List[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}" width="{width}" height="{height}">'
        ),
    ]
    for comment in header_comments:
        lines.append(f"  <!-- {comment} -->")

    for color, rects in color_groups.items():
        rects.sort(key=lambda r: (r[1], r[0]))

        merged: List[Tuple[int, int, int, int]] = []
        for rect in rects:
            x, y, w, h = rect
            if (
                merged
                and merged[-1][1] == y
                and merged[-1][3] == h
                and merged[-1][0] + merged[-1][2] == x
            ):
                last = merged[-1]
                merged[-1] = (last[0], y, last[2] + w, h)
            else:
                merged.append(rect)

        lines.append(f'  <g fill="{color}">')
        for x, y, w, h in merged:
            lines.append(f'    <rect x="{x}" y="{y}" width="{w}" height="{h}"/>')
        lines.append("  </g>")

    lines.append("</svg>")
    return "\n".join(lines)
