#!/usr/bin/env python3
"""svg_core - منطق تحويل الصور إلى SVG (مشترك بين تطبيق سطح المكتب والويب).

This module owns the canonical bitmap-to-SVG conversion algorithm. The
JavaScript port lives in ``svg-core.js`` and MUST stay byte-for-byte
identical; ``tests/fixtures/`` holds golden files that both test suites
assert against, so any drift between the two fails CI.

Algorithm (canonical — mirrored exactly in svg-core.js):
    0. Prepare each pixel: composite any transparency onto white (so a logo on
       a transparent background does not turn into a black square), then, in
       ``"bw"`` and ``"grayscale"`` modes, reduce it to one luma value.
       Both steps are integer-only and live HERE rather than in the apps, so
       the two ports agree from the source pixels to the final file.
    1. Split the image into blocks of ``block_size = MAX_BLOCK_SIZE + 1 - detail_level``.
    2. Average pixel colors inside each block (integer floor division).
    3. Posterize each channel to ``color_levels`` values, range-preserving:
       0 stays 0 and 255 stays 255. In ``"bw"`` mode each channel is instead
       re-thresholded at ``BW_THRESHOLD`` so averaging a block of black and
       white pixels cannot leak grays into a mode that is meant to be binary.
    4. Run-length-encode each block row horizontally.
    5. Merge each run with the run directly above it when color, x and width
       match, producing rectangles merged in BOTH axes.
    6. Emit ``<g fill="...">`` groups in first-appearance order.

All arithmetic in steps 0-3 is integer-only and uses non-negative operands, so
Python's ``//`` and JavaScript's ``Math.floor(a / b)`` agree exactly.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Literal

from PIL import Image

try:  # NumPy is optional: it only accelerates step 2, never changes the output.
    import numpy as np

    _HAS_NUMPY = True
except ImportError:  # pragma: no cover - depends on environment
    np = None  # type: ignore[assignment]
    _HAS_NUMPY = False

__all__ = [
    "BW_THRESHOLD",
    "ConversionType",
    "DEFAULT_COLOR_LEVELS",
    "DEFAULT_DETAIL_LEVEL",
    "DEFAULT_HEADER_COMMENTS",
    "MAX_BLOCK_SIZE",
    "MAX_COLOR_LEVELS",
    "MAX_BLOCKS",
    "MAX_DETAIL_LEVEL",
    "MIN_COLOR_LEVELS",
    "MIN_DETAIL_LEVEL",
    "VALID_CONVERSION_TYPES",
    "OutputTooComplexError",
    "block_count",
    "create_svg",
    "flatten_channel",
    "gray_value",
    "numpy_available",
    "prepare_image",
    "preview_image",
    "quantize_channel",
    "threshold_channel",
]

ConversionType = Literal["color", "bw", "grayscale"]

VALID_CONVERSION_TYPES = ("color", "bw", "grayscale")

#: Grayscale value at or above which a pixel becomes white in "bw" mode.
BW_THRESHOLD = 128

#: Largest block edge, reached at ``detail_level == MIN_DETAIL_LEVEL``.
#: ``block_size = MAX_BLOCK_SIZE + 1 - detail_level``, so detail 1 -> 10px
#: blocks (coarse) and detail 10 -> 1px blocks (every pixel kept).
MAX_BLOCK_SIZE = 10

MIN_DETAIL_LEVEL = 1
MAX_DETAIL_LEVEL = 10
DEFAULT_DETAIL_LEVEL = 5

#: Number of distinct values kept per RGB channel. The resulting palette holds
#: ``color_levels ** 3`` colors (2 -> 8 colors, 6 -> 216 colors).
MIN_COLOR_LEVELS = 2
MAX_COLOR_LEVELS = 6
DEFAULT_COLOR_LEVELS = 3

#: Upper bound on ``block_count()``. Output size grows with the number of
#: blocks, not with the source pixels: noisy input costs ~49 bytes per block,
#: so this caps the worst case near 200 MB — inside V8's maximum string length
#: and far from exhausting a browser tab or the desktop app's memory.
MAX_BLOCKS = 4_000_000

#: ITU-R BT.601 luma weights, in thousandths (integer math keeps parity).
GRAY_WEIGHTS = (299, 587, 114)

#: The generated file belongs to the user, so it only says what made it.
DEFAULT_HEADER_COMMENTS: tuple[str, ...] = ("Generated by محول SVG",)


class OutputTooComplexError(ValueError):
    """The requested settings would produce more than ``MAX_BLOCKS`` blocks."""

    def __init__(self, blocks: int):
        super().__init__(
            f"output would contain {blocks} blocks, more than the limit of {MAX_BLOCKS}"
        )
        self.blocks = blocks


def numpy_available() -> bool:
    """Whether the NumPy fast path for block averaging is usable."""
    return _HAS_NUMPY


def block_count(width: int, height: int, detail_level: int) -> int:
    """Number of blocks (an upper bound on rectangles) for these settings."""
    block_size = MAX_BLOCK_SIZE + 1 - detail_level
    return -(-width // block_size) * -(-height // block_size)


def flatten_channel(value: int, alpha: int) -> int:
    """Composite one channel with opacity ``alpha`` onto white, rounded half-up."""
    return (value * alpha + 255 * (255 - alpha) + 127) // 255


def gray_value(r: int, g: int, b: int) -> int:
    """Integer BT.601 luma, rounded half-up. Mirrored in svg-core.js."""
    return (r * GRAY_WEIGHTS[0] + g * GRAY_WEIGHTS[1] + b * GRAY_WEIGHTS[2] + 500) // 1000


def _has_alpha(img) -> bool:
    return img.mode in ("RGBA", "LA", "PA", "RGBa", "La") or img.has_transparency_data


#: Rows processed per NumPy chunk in ``prepare_image``; bounds the uint32
#: temporaries to a few MB instead of 16 bytes per pixel of the whole image.
_PREPARE_CHUNK_ROWS = 256


def prepare_image(img, conversion_type: ConversionType):
    """Step 0: flatten transparency onto white and apply the luma filter.

    Returns an ``"RGB"`` image in ``"color"`` mode and an ``"L"`` image in
    ``"bw"`` / ``"grayscale"`` mode (``"bw"`` is thresholded later, per block,
    so averaging cannot leak grays — see :func:`threshold_channel`).
    """
    gray = conversion_type != "color"
    alpha = _has_alpha(img)

    if not alpha and not gray:
        return img if img.mode == "RGB" else img.convert("RGB")
    if not alpha and img.mode == "L":
        return img

    src = img.convert("RGBA" if alpha else "RGB")
    width, height = src.size
    out_mode = "L" if gray else "RGB"

    if _HAS_NUMPY:
        arr = np.asarray(src, dtype=np.uint8)
        out = np.empty((height, width) if gray else (height, width, 3), dtype=np.uint8)
        weights = np.asarray(GRAY_WEIGHTS, dtype=np.uint32)
        for top in range(0, height, _PREPARE_CHUNK_ROWS):
            chunk = arr[top : top + _PREPARE_CHUNK_ROWS].astype(np.uint32)
            rgb = chunk[:, :, :3]
            if alpha:
                a = chunk[:, :, 3:4]
                rgb = (rgb * a + 255 * (255 - a) + 127) // 255
            if gray:
                out[top : top + _PREPARE_CHUNK_ROWS] = (rgb @ weights + 500) // 1000
            else:
                out[top : top + _PREPARE_CHUNK_ROWS] = rgb
        return Image.fromarray(out, out_mode)

    raw = src.tobytes()
    step = 4 if alpha else 3
    out_bytes = bytearray(width * height * (1 if gray else 3))
    o = 0
    for i in range(0, len(raw), step):
        r, g, b = raw[i], raw[i + 1], raw[i + 2]
        if alpha:
            a = raw[i + 3]
            r, g, b = flatten_channel(r, a), flatten_channel(g, a), flatten_channel(b, a)
        if gray:
            out_bytes[o] = gray_value(r, g, b)
            o += 1
        else:
            out_bytes[o : o + 3] = bytes((r, g, b))
            o += 3
    return Image.frombytes(out_mode, (width, height), bytes(out_bytes))


def quantize_channel(value: int, color_levels: int) -> int:
    """Posterize one 0-255 channel to ``color_levels`` evenly spaced values.

    Unlike naive ``(v // step) * step`` truncation, this is range-preserving:
    ``0`` maps to ``0`` and ``255`` maps to ``255`` for every level count, so
    whites stay white instead of collapsing to mid-gray.

    Written with integer half-up rounding (no floats) so the JavaScript port
    produces identical bytes.
    """
    steps = color_levels - 1
    # round(value * steps / 255), half-up
    index = (value * steps * 2 + 255) // 510
    # round(index * 255 / steps), half-up
    return (index * 510 + steps) // (steps * 2)


def _block_bounds(size: int, block_size: int) -> tuple[list[int], list[int]]:
    """Return (starts, ends) of the blocks covering ``size`` pixels."""
    starts = list(range(0, size, block_size))
    ends = [min(start + block_size, size) for start in starts]
    return starts, ends


def _grid_python(
    pixels,
    starts_x: Sequence[int],
    ends_x: Sequence[int],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
) -> list[list[tuple[int, int, int]]]:
    """Average each block with plain Python. Reference implementation."""
    grid: list[list[tuple[int, int, int]]] = []
    for y0, y1 in zip(starts_y, ends_y):
        row: list[tuple[int, int, int]] = []
        for x0, x1 in zip(starts_x, ends_x):
            r_sum = g_sum = b_sum = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    pixel = pixels[x, y]
                    r_sum += pixel[0]
                    g_sum += pixel[1]
                    b_sum += pixel[2]
            count = (y1 - y0) * (x1 - x0)
            row.append((r_sum // count, g_sum // count, b_sum // count))
        grid.append(row)
    return grid


def _grid_numpy(
    img,
    starts_x: Sequence[int],
    ends_x: Sequence[int],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
):
    """Average each block with NumPy — same integer result, much faster.

    Measured end-to-end on 1200x900 images: 3-6x on high-noise input, 6-12x on
    photographic or flat artwork. (Block averaging is what this removes; the
    run-length and merge passes stay in Python and dominate on noisy input.)


    ``np.add.reduceat`` sums the half-open segments ``[starts[i], starts[i+1])``
    and runs the final segment to the end of the axis, which is exactly the
    block layout including the partial blocks at the right/bottom edges.
    Summing with ``dtype=uint32`` keeps the source array as uint8: a block holds
    at most ``MAX_BLOCK_SIZE ** 2 * 255 = 25500``, so it cannot overflow.
    """
    arr = np.asarray(img, dtype=np.uint8)
    if arr.ndim != 3 or arr.shape[2] < 3:  # pragma: no cover - guarded by caller
        raise ValueError("expected an RGB image array")
    arr = arr[:, :, :3]

    row_sums = np.add.reduceat(arr, np.asarray(starts_y), axis=0, dtype=np.uint32)
    block_sums = np.add.reduceat(row_sums, np.asarray(starts_x), axis=1, dtype=np.uint32)

    heights = np.asarray(ends_y, dtype=np.uint32) - np.asarray(starts_y, dtype=np.uint32)
    widths = np.asarray(ends_x, dtype=np.uint32) - np.asarray(starts_x, dtype=np.uint32)
    counts = heights[:, None] * widths[None, :]

    return block_sums // counts[:, :, None]


def threshold_channel(value: int) -> int:
    """Snap one channel back to pure black or white for ``"bw"`` mode."""
    return 255 if value >= BW_THRESHOLD else 0


def _posterize_grid_numpy(grid, conversion_type: ConversionType, color_levels: int):
    """Vectorized step 3 over a whole block grid."""
    if conversion_type == "bw":
        return np.where(grid >= BW_THRESHOLD, 255, 0)
    steps = color_levels - 1
    index = (grid * (steps * 2) + 255) // 510
    return (index * 510 + steps) // (steps * 2)


def _row_runs(
    row: Sequence[Sequence[int]],
    starts_x: Sequence[int],
    ends_x: Sequence[int],
) -> list[tuple[int, int, tuple[int, int, int]]]:
    """Run-length-encode one block row into (x, width, rgb) runs."""
    runs: list[tuple[int, int, tuple[int, int, int]]] = []
    count = len(row)
    start = 0
    while start < count:
        end = start + 1
        while (
            end < count
            and row[end][0] == row[start][0]
            and row[end][1] == row[start][1]
            and row[end][2] == row[start][2]
        ):
            end += 1
        color = row[start]
        runs.append(
            (
                starts_x[start],
                ends_x[end - 1] - starts_x[start],
                (int(color[0]), int(color[1]), int(color[2])),
            )
        )
        start = end
    return runs


def _merge_vertically(
    rows: Iterable[list[tuple[int, int, tuple[int, int, int]]]],
    starts_y: Sequence[int],
    ends_y: Sequence[int],
) -> dict[str, list[list[int]]]:
    """Merge each run into the run above it, then group rectangles by color.

    Groups keep first-appearance order and rectangles keep (y, x) order, which
    makes the output byte-stable across runs and across languages.
    """
    groups: dict[str, list[list[int]]] = {}
    open_rects: dict[tuple[int, int, str], list[int]] = {}

    for band, runs in enumerate(rows):
        y0 = starts_y[band]
        height = ends_y[band] - y0
        next_open: dict[tuple[int, int, str], list[int]] = {}

        for x, width, rgb in runs:
            color = f"rgb({rgb[0]},{rgb[1]},{rgb[2]})"
            key = (x, width, color)
            rect = open_rects.get(key)
            if rect is not None and rect[1] + rect[3] == y0:
                rect[3] += height
            else:
                rect = [x, y0, width, height]
                groups.setdefault(color, []).append(rect)
            next_open[key] = rect

        open_rects = next_open

    return groups


def _emit_svg(
    width: int,
    height: int,
    groups: dict[str, list[list[int]]],
    header_comments: Iterable[str],
) -> str:
    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}" width="{width}" height="{height}" '
            f'shape-rendering="crispEdges">'
        ),
    ]
    for comment in header_comments:
        lines.append(f"  <!-- {comment} -->")

    for color, rects in groups.items():
        lines.append(f'  <g fill="{color}">')
        for x, y, rect_w, rect_h in rects:
            lines.append(f'    <rect x="{x}" y="{y}" width="{rect_w}" height="{rect_h}"/>')
        lines.append("  </g>")

    lines.append("</svg>")
    return "\n".join(lines)


def _validate(conversion_type, color_levels: int, detail_level: int) -> None:
    if conversion_type not in VALID_CONVERSION_TYPES:
        raise ValueError(
            f"conversion_type must be one of {VALID_CONVERSION_TYPES}, got {conversion_type!r}"
        )
    if not MIN_COLOR_LEVELS <= color_levels <= MAX_COLOR_LEVELS:
        raise ValueError(
            f"color_levels must be between {MIN_COLOR_LEVELS} and {MAX_COLOR_LEVELS}, "
            f"got {color_levels!r}"
        )
    if not MIN_DETAIL_LEVEL <= detail_level <= MAX_DETAIL_LEVEL:
        raise ValueError(
            f"detail_level must be between {MIN_DETAIL_LEVEL} and {MAX_DETAIL_LEVEL}, "
            f"got {detail_level!r}"
        )


def _posterized_grid(img, conversion_type, color_levels: int, detail_level: int):
    """Steps 0-3: validate, prepare pixels, average blocks and posterize.

    Returns ``(rows, starts_x, ends_x, starts_y, ends_y)`` where ``rows`` is a
    list of block rows, each a list of ``[r, g, b]`` integer triples.
    """
    _validate(conversion_type, color_levels, detail_level)

    width, height = img.size
    if width <= 0 or height <= 0:
        raise ValueError(f"image must not be empty, got {width}x{height}")
    blocks = block_count(width, height, detail_level)
    if blocks > MAX_BLOCKS:
        raise OutputTooComplexError(blocks)

    img = prepare_image(img, conversion_type)
    if img.mode != "RGB":
        img = img.convert("RGB")

    block_size = MAX_BLOCK_SIZE + 1 - detail_level
    starts_x, ends_x = _block_bounds(width, block_size)
    starts_y, ends_y = _block_bounds(height, block_size)

    if _HAS_NUMPY:
        grid = _grid_numpy(img, starts_x, ends_x, starts_y, ends_y)
        rows = _posterize_grid_numpy(grid, conversion_type, color_levels).tolist()
    else:
        if conversion_type == "bw":

            def posterize(value: int) -> int:
                return threshold_channel(value)
        else:

            def posterize(value: int) -> int:
                return quantize_channel(value, color_levels)

        rows = [
            [[posterize(r), posterize(g), posterize(b)] for r, g, b in band]
            for band in _grid_python(img.load(), starts_x, ends_x, starts_y, ends_y)
        ]
    return rows, starts_x, ends_x, starts_y, ends_y


def create_svg(
    img,
    conversion_type: ConversionType,
    color_levels: int = DEFAULT_COLOR_LEVELS,
    detail_level: int = DEFAULT_DETAIL_LEVEL,
    header_comments: Iterable[str] = DEFAULT_HEADER_COMMENTS,
) -> str:
    """Convert a PIL Image into an SVG string.

    Args:
        img: A PIL ``Image`` in any mode. Transparency is composited onto
            white and ``"bw"`` / ``"grayscale"`` apply the luma filter here,
            so callers pass the source image untouched.
        conversion_type: ``"color"``, ``"bw"``, or ``"grayscale"``.
        color_levels: Values kept per RGB channel (2-6); the palette holds
            ``color_levels ** 3`` colors. Ignored for ``"bw"``.
        detail_level: 1-10; higher = smaller blocks = more detail.
        header_comments: Comments injected at the top of the SVG.

    Returns:
        A UTF-8 SVG document as a string.

    Raises:
        OutputTooComplexError: when the settings exceed ``MAX_BLOCKS``.
        ValueError: on an unknown ``conversion_type``, an out-of-range
            ``color_levels`` / ``detail_level``, or an empty image.
    """
    rows, starts_x, ends_x, starts_y, ends_y = _posterized_grid(
        img, conversion_type, color_levels, detail_level
    )
    runs = (_row_runs(band, starts_x, ends_x) for band in rows)
    groups = _merge_vertically(runs, starts_y, ends_y)
    return _emit_svg(img.size[0], img.size[1], groups, header_comments)


def _scaled_spans(ends: Sequence[int], scale: float) -> list[int]:
    """Block extents after scaling by ``scale``; some may shrink to zero."""
    scaled = [round(end * scale) for end in ends]
    scaled[-1] = max(1, scaled[-1])
    return [end - start for start, end in zip([0, *scaled[:-1]], scaled)]


def preview_image(
    img,
    conversion_type: ConversionType,
    color_levels: int = DEFAULT_COLOR_LEVELS,
    detail_level: int = DEFAULT_DETAIL_LEVEL,
    max_pixels: int = 4_000_000,
) -> Image.Image:
    """Rasterize exactly what :func:`create_svg` would draw, without an SVG renderer.

    Every block is painted with the very color ``create_svg`` gives its
    rectangle. Images above ``max_pixels`` are rendered proportionally smaller
    (block edges are scaled, not resampled), which is plenty for a preview pane.
    """
    rows, _sx, ends_x, _sy, ends_y = _posterized_grid(
        img, conversion_type, color_levels, detail_level
    )
    width, height = img.size
    scale = min(1.0, (max_pixels / (width * height)) ** 0.5)
    widths = _scaled_spans(ends_x, scale)
    heights = _scaled_spans(ends_y, scale)

    data = b"".join(
        b"".join(bytes(color) * span for color, span in zip(row, widths)) * row_height
        for row, row_height in zip(rows, heights)
    )
    return Image.frombytes("RGB", (sum(widths), sum(heights)), data)
