/**
 * End-to-end tests for the web app (index.html + app.js + svg-worker.js),
 * driven through a real Chromium with Playwright:
 *
 *   npm ci && npx playwright install chromium
 *   node --test tests/e2e/
 *
 * Test images are drawn on a canvas inside the page and handed back to
 * Playwright, so no binary fixtures live in the repository.
 */
"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const { chromium } = require("playwright");

const ROOT = path.resolve(__dirname, "..", "..");
const TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
};

let server;
let baseUrl;
let browser;

test.before(async () => {
    server = http.createServer((req, res) => {
        const urlPath = decodeURIComponent(new URL(req.url, "http://x").pathname);
        const file = path.join(ROOT, urlPath === "/" ? "index.html" : urlPath);
        if (!file.startsWith(ROOT) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
            res.writeHead(404).end();
            return;
        }
        res.writeHead(200, { "Content-Type": TYPES[path.extname(file)] || "application/octet-stream" });
        fs.createReadStream(file).pipe(res);
    });
    await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
    baseUrl = `http://127.0.0.1:${server.address().port}/`;
    browser = await chromium.launch(
        process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}
    );
});

test.after(async () => {
    if (browser) await browser.close();
    if (server) server.close();
});

/** Open the app and collect CSP violations and uncaught errors. */
async function openApp() {
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();
    const problems = [];
    page.on("console", (msg) => {
        if (/Content Security Policy|Refused to/i.test(msg.text())) problems.push(msg.text());
    });
    page.on("pageerror", (err) => problems.push(String(err)));
    await page.goto(baseUrl);
    return { page, problems, close: () => context.close() };
}

/**
 * Draw an image in the page and return it as a file payload for setInputFiles.
 * kind: "logo" (black square on transparent), "solid" (opaque red), "noise".
 */
async function makeImage(page, kind, size, mimeType) {
    const dataUrl = await page.evaluate(
        ({ kind, size, mimeType }) => {
            const canvas = document.createElement("canvas");
            canvas.width = canvas.height = size;
            const ctx = canvas.getContext("2d");
            if (kind === "logo") {
                ctx.fillStyle = "#000";
                ctx.fillRect(size / 4, size / 4, size / 2, size / 2);
            } else if (kind === "solid") {
                ctx.fillStyle = "#f00";
                ctx.fillRect(0, 0, size, size);
            } else {
                const img = ctx.createImageData(size, size);
                for (let i = 0; i < img.data.length; i++) {
                    img.data[i] = (i % 4 === 3) ? 255 : (Math.random() * 256) | 0;
                }
                ctx.putImageData(img, 0, 0);
            }
            return canvas.toDataURL(mimeType);
        },
        { kind, size, mimeType }
    );
    const ext = mimeType === "image/png" ? "png" : "jpg";
    return {
        name: `${kind}.${ext}`,
        mimeType,
        buffer: Buffer.from(dataUrl.split(",")[1], "base64"),
    };
}

async function upload(page, file) {
    await page.setInputFiles("#fileInput", file);
    await page.waitForSelector("#previewSection:not([hidden])");
}

async function convertAndDownload(page) {
    await page.click("#convertBtn");
    await page.waitForSelector("#statusMessage.success");
    const [download] = await Promise.all([
        page.waitForEvent("download"),
        page.click("#downloadBtn"),
    ]);
    const svg = fs.readFileSync(await download.path(), "utf8");
    return { svg, name: download.suggestedFilename() };
}

function fills(svg) {
    return [...new Set([...svg.matchAll(/fill="([^"]+)"/g)].map((m) => m[1]))].sort();
}

test("a transparent logo converts to black on white, not a black square", async () => {
    const { page, problems, close } = await openApp();
    try {
        await upload(page, await makeImage(page, "logo", 40, "image/png"));
        await page.check('input[name="conversionType"][value="bw"]', { force: true });
        const { svg, name } = await convertAndDownload(page);
        assert.equal(name, "logo.svg");
        assert.deepEqual(fills(svg), ["rgb(0,0,0)", "rgb(255,255,255)"]);
        assert.ok(svg.includes("<!-- Generated by محول SVG -->"));
        assert.ok(!svg.includes("All Rights Reserved"));
        assert.deepEqual(problems, []);
    } finally {
        await close();
    }
});

test("controls lock during conversion; cancel stops it and its result never lands", async () => {
    const { page, problems, close } = await openApp();
    try {
        await upload(page, await makeImage(page, "noise", 1600, "image/jpeg"));
        await page.locator("#detailLevel").fill("10");
        await page.locator("#colorLevels").fill("6");
        await page.click("#convertBtn");

        await page.waitForSelector("#cancelBtn:not([hidden])");
        assert.equal(await page.isDisabled("#newImageBtn"), true);
        assert.equal(await page.isDisabled("#convertBtn"), true);
        assert.equal(await page.isDisabled("#downloadBtn"), true);

        // Ctrl+O must not open the picker mid-conversion.
        let chooserOpened = false;
        page.once("filechooser", () => { chooserOpened = true; });
        await page.keyboard.press("Control+o");
        await page.waitForTimeout(300);
        assert.equal(chooserOpened, false);

        await page.click("#cancelBtn");
        await page.waitForSelector("#statusMessage.info");
        assert.equal(await page.isDisabled("#newImageBtn"), false);
        assert.equal(await page.isDisabled("#downloadBtn"), true);
        assert.equal(await page.isHidden("#cancelBtn"), true);

        // A different image now, converted for real.
        await page.click("#newImageBtn");
        await upload(page, await makeImage(page, "solid", 30, "image/png"));
        await page.locator("#detailLevel").fill("5");
        const { svg, name } = await convertAndDownload(page);
        assert.equal(name, "solid.svg");
        assert.deepEqual(fills(svg), ["rgb(255,0,0)"]);

        // The cancelled conversion must not overwrite it later.
        await page.waitForTimeout(500);
        const [again] = await Promise.all([
            page.waitForEvent("download"),
            page.click("#downloadBtn"),
        ]);
        assert.deepEqual(fills(fs.readFileSync(await again.path(), "utf8")), ["rgb(255,0,0)"]);
        assert.deepEqual(problems, []);
    } finally {
        await close();
    }
});

test("changing a setting marks the shown result as stale", async () => {
    const { page, close } = await openApp();
    try {
        await upload(page, await makeImage(page, "solid", 30, "image/png"));
        await page.click("#convertBtn");
        await page.waitForSelector("#statusMessage.success");
        assert.ok(!(await page.textContent("#svgMeta")).includes("تغيّرت"));

        await page.locator("#detailLevel").fill("9");
        assert.ok((await page.textContent("#svgMeta")).includes("الإعدادات تغيّرت"));
        assert.equal(await page.isVisible("#statusMessage"), false);

        await page.locator("#detailLevel").fill("5");
        assert.ok(!(await page.textContent("#svgMeta")).includes("تغيّرت"));
    } finally {
        await close();
    }
});

test("settings that would build a huge SVG are refused up front", async () => {
    const { page, close } = await openApp();
    try {
        await upload(page, await makeImage(page, "solid", 1500, "image/png"));
        await page.locator("#detailLevel").fill("10");
        await page.check('input[name="outputScale"][value="2"]', { force: true });
        await page.click("#convertBtn");
        await page.waitForSelector("#statusMessage.error");
        assert.match(await page.textContent("#statusMessage"), /معقّداً جداً/);
        assert.equal(await page.isDisabled("#convertBtn"), false);
    } finally {
        await close();
    }
});

test("an SVG file is rejected with a clear message", async () => {
    const { page, close } = await openApp();
    try {
        await page.setInputFiles("#fileInput", {
            name: "already.svg",
            mimeType: "image/svg+xml",
            buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>'),
        });
        await page.waitForSelector("#statusMessage.error");
        assert.match(await page.textContent("#statusMessage"), /SVG أصلاً/);
        assert.equal(await page.isHidden("#previewSection"), true);
    } finally {
        await close();
    }
});
